using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace CloudheadGames.Darkspace.EditorTools
{
	public class BulkLODGroupEditorWindow : EditorWindow
	{
		private readonly List<Object> _targets = new();

		private Vector2 _scroll;

		private bool _includeChildren = true;
		private bool _recalculateBounds = true;

		private readonly List<float> _lodTransitions = new()
		{
			0.55f,
			0.35f,
			0.22f,
			0.12f,
			0.045f
		};

		private float _autoGeneratedFalloffMultiplier = 0.5f;
		private float _minimumTransition = 0.001f;

		private bool _setFadeWidth;
		private float _fadeWidth = 0.1f;

		[MenuItem("Edit/Bulk LODGroup Editor")]
		public static void Open()
		{
			GetWindow<BulkLODGroupEditorWindow>("Bulk LODGroup Editor");
		}

		private void OnGUI()
		{
			_scroll = EditorGUILayout.BeginScrollView(_scroll);

			EditorGUILayout.Space(8f);

			EditorGUILayout.LabelField("Sources", EditorStyles.boldLabel);

			DrawTargetDropArea();

			EditorGUILayout.Space(6f);

			using (new EditorGUILayout.HorizontalScope())
			{
				if (GUILayout.Button("Add Selection"))
					AddSelection();

				if (GUILayout.Button("Clear"))
					_targets.Clear();
			}

			EditorGUILayout.Space(8f);

			DrawTargetList();

			EditorGUILayout.Space(12f);

			EditorGUILayout.LabelField("LOD Transition Profile", EditorStyles.boldLabel);

			EditorGUILayout.HelpBox(
				"Unity stores the final cull threshold as the transition height of the last actual LOD entry. For example, a mesh with LOD0-LOD4 plus cull has 5 LOD entries, and LOD4's transition controls when it culls.",
				MessageType.Info);

			for (int i = 0; i < _lodTransitions.Count; i++)
			{
				using (new EditorGUILayout.HorizontalScope())
				{
					string label = i == _lodTransitions.Count - 1
						? $"LOD {i} / Cull Transition"
						: $"LOD {i} Transition";

					_lodTransitions[i] = EditorGUILayout.Slider(label, _lodTransitions[i], 0.001f, 1f);

					using (new EditorGUI.DisabledScope(_lodTransitions.Count <= 1))
					{
						if (GUILayout.Button("-", GUILayout.Width(24f)))
						{
							_lodTransitions.RemoveAt(i);
							break;
						}
					}
				}
			}

			using (new EditorGUILayout.HorizontalScope())
			{
				if (GUILayout.Button("Add LOD Slot"))
				{
					float previous = _lodTransitions.Count > 0
						? _lodTransitions[^1]
						: 0.1f;

					_lodTransitions.Add(Mathf.Max(_minimumTransition, previous * _autoGeneratedFalloffMultiplier));
				}

				if (GUILayout.Button("Reset 3 LODs"))
				{
					_lodTransitions.Clear();
					_lodTransitions.Add(0.45f);
					_lodTransitions.Add(0.22f);
					_lodTransitions.Add(0.045f);
				}

				if (GUILayout.Button("Reset 5 LODs"))
				{
					_lodTransitions.Clear();
					_lodTransitions.Add(0.55f);
					_lodTransitions.Add(0.35f);
					_lodTransitions.Add(0.22f);
					_lodTransitions.Add(0.12f);
					_lodTransitions.Add(0.045f);
				}
			}

			_autoGeneratedFalloffMultiplier = EditorGUILayout.Slider(
				"Extra LOD Falloff Multiplier",
				_autoGeneratedFalloffMultiplier,
				0.1f,
				0.95f);

			_minimumTransition = EditorGUILayout.Slider(
				"Minimum Transition",
				_minimumTransition,
				0.001f,
				0.05f);

			EditorGUILayout.Space(12f);

			using (new EditorGUILayout.HorizontalScope())
			{
				if (GUILayout.Button("Apply To Targets", GUILayout.Height(32f)))
					ApplyToTargets();

				if (GUILayout.Button("Apply To Selection", GUILayout.Height(32f)))
				{
					AddSelection();
					ApplyToTargets();
				}
			}

			EditorGUILayout.Space(16f);

			EditorGUILayout.EndScrollView();
		}

		private void DrawTargetDropArea()
		{
			Rect dropRect = GUILayoutUtility.GetRect(0f, 70f, GUILayout.ExpandWidth(true));

			GUI.Box(dropRect, "Drag prefab assets, scene objects, or folders here", EditorStyles.helpBox);

			Event current = Event.current;

			if (!dropRect.Contains(current.mousePosition))
				return;

			if (current.type != EventType.DragUpdated && current.type != EventType.DragPerform)
				return;

			DragAndDrop.visualMode = DragAndDropVisualMode.Copy;

			if (current.type == EventType.DragPerform)
			{
				DragAndDrop.AcceptDrag();

				foreach (Object draggedObject in DragAndDrop.objectReferences)
					AddTarget(draggedObject);
			}

			current.Use();
		}

		private void DrawTargetList()
		{
			EditorGUILayout.LabelField($"Targets: {_targets.Count}", EditorStyles.miniBoldLabel);

			if (_targets.Count == 0)
			{
				EditorGUILayout.HelpBox("No targets added yet.", MessageType.None);
				return;
			}

			for (int i = _targets.Count - 1; i >= 0; i--)
			{
				using (new EditorGUILayout.HorizontalScope())
				{
					_targets[i] = EditorGUILayout.ObjectField(_targets[i], typeof(Object), true);

					if (GUILayout.Button("X", GUILayout.Width(24f)))
						_targets.RemoveAt(i);
				}
			}
		}

		private void AddSelection()
		{
			foreach (Object selectedObject in Selection.objects)
				AddTarget(selectedObject);
		}

		private void AddTarget(Object target)
		{
			if (target == null)
				return;

			if (_targets.Contains(target))
				return;

			_targets.Add(target);
		}

		private void ApplyToTargets()
		{
			int lodGroupsChanged = 0;
			int prefabAssetsChanged = 0;
			int sceneObjectsChanged = 0;

			HashSet<string> processedPrefabPaths = new();

			foreach (Object target in _targets)
			{
				if (target == null)
					continue;

				string assetPath = AssetDatabase.GetAssetPath(target);

				if (!string.IsNullOrEmpty(assetPath) && AssetDatabase.IsValidFolder(assetPath))
				{
					ProcessFolder(assetPath, processedPrefabPaths, ref lodGroupsChanged, ref prefabAssetsChanged);
					continue;
				}

				if (!string.IsNullOrEmpty(assetPath) && IsPrefabAssetPath(assetPath))
				{
					ProcessPrefabAsset(assetPath, processedPrefabPaths, ref lodGroupsChanged, ref prefabAssetsChanged);
					continue;
				}

				if (target is GameObject sceneObject)
				{
					lodGroupsChanged += ProcessSceneObject(sceneObject);

					if (lodGroupsChanged > 0)
						sceneObjectsChanged++;

					continue;
				}

				if (target is LODGroup lodGroup)
				{
					ApplyToSceneLODGroup(lodGroup);
					lodGroupsChanged++;
					sceneObjectsChanged++;
				}
			}

			AssetDatabase.SaveAssets();
			AssetDatabase.Refresh();

			Debug.Log(
				$"Bulk LODGroup Editor complete. Changed {lodGroupsChanged} LODGroups. Prefab assets: {prefabAssetsChanged}. Scene objects: {sceneObjectsChanged}.");
		}

		private static bool IsPrefabAssetPath(string assetPath)
		{
			return !string.IsNullOrEmpty(assetPath)
				   && assetPath.EndsWith(".prefab", System.StringComparison.OrdinalIgnoreCase);
		}
		
		private void ProcessFolder(
			string folderPath,
			HashSet<string> processedPrefabPaths,
			ref int lodGroupsChanged,
			ref int prefabAssetsChanged)
		{
			string[] guids = AssetDatabase.FindAssets("t:Prefab", new[] { folderPath });

			foreach (string guid in guids)
			{
				string prefabPath = AssetDatabase.GUIDToAssetPath(guid);
				ProcessPrefabAsset(prefabPath, processedPrefabPaths, ref lodGroupsChanged, ref prefabAssetsChanged);
			}
		}

		private void ProcessPrefabAsset(
			string prefabPath,
			HashSet<string> processedPrefabPaths,
			ref int lodGroupsChanged,
			ref int prefabAssetsChanged)
		{
			if (string.IsNullOrEmpty(prefabPath))
				return;

			if (!processedPrefabPaths.Add(prefabPath))
				return;

			GameObject prefabRoot = PrefabUtility.LoadPrefabContents(prefabPath);

			try
			{
				LODGroup[] lodGroups = GetLODGroups(prefabRoot);

				if (lodGroups.Length == 0)
					return;

				foreach (LODGroup lodGroup in lodGroups)
				{
					ApplyToLODGroup(lodGroup);
					lodGroupsChanged++;
				}

				PrefabUtility.SaveAsPrefabAsset(prefabRoot, prefabPath);
				prefabAssetsChanged++;
			}
			finally
			{
				PrefabUtility.UnloadPrefabContents(prefabRoot);
			}
		}

		private int ProcessSceneObject(GameObject sceneObject)
		{
			LODGroup[] lodGroups = GetLODGroups(sceneObject);

			foreach (LODGroup lodGroup in lodGroups)
				ApplyToSceneLODGroup(lodGroup);

			return lodGroups.Length;
		}

		private LODGroup[] GetLODGroups(GameObject root)
		{
			if (root == null)
				return new LODGroup[0];

			if (_includeChildren)
				return root.GetComponentsInChildren<LODGroup>(true);

			LODGroup lodGroup = root.GetComponent<LODGroup>();

			if (lodGroup == null)
				return new LODGroup[0];

			return new[] { lodGroup };
		}

		private void ApplyToSceneLODGroup(LODGroup lodGroup)
		{
			if (lodGroup == null)
				return;

			Undo.RecordObject(lodGroup, "Bulk Edit LODGroup");
			ApplyToLODGroup(lodGroup);
			EditorUtility.SetDirty(lodGroup);
		}

		private void ApplyToLODGroup(LODGroup lodGroup)
		{
			if (lodGroup == null)
				return;

			LOD[] lods = lodGroup.GetLODs();

			if (lods == null || lods.Length == 0)
				return;

			EnsureProfileHasValidTransitions();

			for (int i = 0; i < lods.Length; i++)
			{
				lods[i].screenRelativeTransitionHeight = GetTransitionForLODIndex(i);

				if (_setFadeWidth)
					lods[i].fadeTransitionWidth = _fadeWidth;
			}

			EnsureDescendingTransitions(lods);

			lodGroup.SetLODs(lods);

			if (_recalculateBounds)
				lodGroup.RecalculateBounds();
		}

		private float GetTransitionForLODIndex(int lodIndex)
		{
			if (_lodTransitions.Count == 0)
				return _minimumTransition;

			if (lodIndex < _lodTransitions.Count)
				return Mathf.Clamp(_lodTransitions[lodIndex], _minimumTransition, 1f);

			float value = _lodTransitions[^1];

			for (int i = _lodTransitions.Count; i <= lodIndex; i++)
				value *= _autoGeneratedFalloffMultiplier;

			return Mathf.Clamp(value, _minimumTransition, 1f);
		}

		private void EnsureProfileHasValidTransitions()
		{
			if (_lodTransitions.Count == 0)
				_lodTransitions.Add(0.045f);

			for (int i = 0; i < _lodTransitions.Count; i++)
				_lodTransitions[i] = Mathf.Clamp(_lodTransitions[i], _minimumTransition, 1f);

			for (int i = 1; i < _lodTransitions.Count; i++)
			{
				float previous = _lodTransitions[i - 1];
				float current = _lodTransitions[i];

				if (current >= previous)
					_lodTransitions[i] = Mathf.Max(_minimumTransition, previous - _minimumTransition);
			}
		}

		private void EnsureDescendingTransitions(LOD[] lods)
		{
			if (lods == null || lods.Length == 0)
				return;

			lods[0].screenRelativeTransitionHeight = Mathf.Clamp(
				lods[0].screenRelativeTransitionHeight,
				_minimumTransition,
				1f);

			for (int i = 1; i < lods.Length; i++)
			{
				float previous = lods[i - 1].screenRelativeTransitionHeight;
				float current = lods[i].screenRelativeTransitionHeight;

				current = Mathf.Clamp(current, _minimumTransition, 1f);

				if (current >= previous)
					current = Mathf.Max(_minimumTransition, previous - _minimumTransition);

				lods[i].screenRelativeTransitionHeight = current;
			}
		}

	}
}
